/****************************************************************************
 *
 *   Copyright (C) 2013-2016 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/* Auto-generated by genmsg_cpp from file /home/guanbin/PX4-Autopilot/msg/xmf_status.msg */


#include <inttypes.h>
#include <px4_platform_common/log.h>
#include <px4_platform_common/defines.h>
#include <uORB/topics/xmf_status.h>
#include <uORB/topics/uORBTopics.hpp>
#include <drivers/drv_hrt.h>
#include <lib/drivers/device/Device.hpp>
#include <lib/matrix/matrix/math.hpp>
#include <lib/mathlib/mathlib.h>

constexpr char __orb_xmf_status_fields[] = "uint64_t timestamp;float xmf_pitch_setpoint;float xmf_roll_setpoint;float xmf_yaw_setpoint;float xmf_pitch_rate;float xmf_roll_rate;float xmf_yaw_rate;float xmf_pitch;float xmf_roll;float xmf_yaw;float xmf_pitch_u;float xmf_roll_u;float xmf_yaw_u;float xmf_pitch_err;float xmf_roll_err;float xmf_yaw_err;uint8_t[4] _padding0;";

ORB_DEFINE(xmf_status, struct xmf_status_s, 68, __orb_xmf_status_fields, static_cast<uint8_t>(ORB_ID::xmf_status));


void print_message(const xmf_status_s &message)
{

	PX4_INFO_RAW(" xmf_status_s\n");

	const hrt_abstime now = hrt_absolute_time();

	if (message.timestamp != 0) {
		PX4_INFO_RAW("\ttimestamp: %" PRIu64 "  (%.6f seconds ago)\n", message.timestamp, (now - message.timestamp) / 1e6);
	} else {
		PX4_INFO_RAW("\n");
	}
	PX4_INFO_RAW("\txmf_pitch_setpoint: %.4f\n", (double)message.xmf_pitch_setpoint);
	PX4_INFO_RAW("\txmf_roll_setpoint: %.4f\n", (double)message.xmf_roll_setpoint);
	PX4_INFO_RAW("\txmf_yaw_setpoint: %.4f\n", (double)message.xmf_yaw_setpoint);
	PX4_INFO_RAW("\txmf_pitch_rate: %.4f\n", (double)message.xmf_pitch_rate);
	PX4_INFO_RAW("\txmf_roll_rate: %.4f\n", (double)message.xmf_roll_rate);
	PX4_INFO_RAW("\txmf_yaw_rate: %.4f\n", (double)message.xmf_yaw_rate);
	PX4_INFO_RAW("\txmf_pitch: %.4f\n", (double)message.xmf_pitch);
	PX4_INFO_RAW("\txmf_roll: %.4f\n", (double)message.xmf_roll);
	PX4_INFO_RAW("\txmf_yaw: %.4f\n", (double)message.xmf_yaw);
	PX4_INFO_RAW("\txmf_pitch_u: %.4f\n", (double)message.xmf_pitch_u);
	PX4_INFO_RAW("\txmf_roll_u: %.4f\n", (double)message.xmf_roll_u);
	PX4_INFO_RAW("\txmf_yaw_u: %.4f\n", (double)message.xmf_yaw_u);
	PX4_INFO_RAW("\txmf_pitch_err: %.4f\n", (double)message.xmf_pitch_err);
	PX4_INFO_RAW("\txmf_roll_err: %.4f\n", (double)message.xmf_roll_err);
	PX4_INFO_RAW("\txmf_yaw_err: %.4f\n", (double)message.xmf_yaw_err);
	
}
